# Set the version of Python
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
# set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements-dev.txt